version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  mirror:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Push to organization repo
          command: |
            git config --global user.name jykim170
            git config --global user.email vertoco@naver.com
            git remote add org https://x-access-token:${ORG_PUSH_PAT}@github.com/SSAFY-15/SW_study_KJY.git
            git push org main --force

workflows:
  say-hello-and-mirror:
    jobs:
      - say-hello
      - mirror:
          requires:
            - say-hello
